
export interface User {
  id: string;
  walletAddress: string;
  username: string;
  avatarUrl: string;
  email?: string;
  bio?: string;
  balance: number; // in USDT (Game Currency)
  spxBalance?: number; // Native Token Balance
  totalHands?: number; // Added for VIP tracking
  friends?: string[]; // List of Friend User IDs
  preferences: {
    showWinRate: boolean;
    showPnL: boolean;
    incognito?: boolean; // New: Mask username on tables
    hideBalance?: boolean; // New: Hide balance on public profile
    allowFriendRequests?: boolean; // New: Social privacy
  };
  isVerified?: boolean;
  // Ecosystem Fields
  referralCode?: string;
  referralRank?: 0 | 1 | 2 | 3; // 0=Scout, 1=Agent, 2=Broker, 3=Partner
  hostRank?: 0 | 1 | 2 | 3 | 4; // 0=Dealer to 4=Mogul
  ecosystemStats?: {
    totalReferrals: number; // Total network size
    directReferrals: number; // Level 1 connections
    networkHands: number; // Total hands played by network
    referralEarnings: number;
    tablesCreated: number;
    hostEarnings: number; // Personal take-home earnings
    totalHostRevenueGenerated: number; // Total rake/fees generated by their tables (for ranking)
    pendingRewards: number;
    // For Rank Tracking
    directAgents: number; // How many directs are Rank 1
    directBrokers: number; // How many directs are Rank 2
  };
  stakingStats?: {
    stakedAmount: number;
    rewardsEarned: number; // Claimable
    totalRewardsClaimed: number; // Lifetime
    apy: number; // Personal effective APY (bonus based on lock time if implemented)
    lastStakedTime?: number; // Timestamp of last deposit (resets cooldown)
  };
}

export enum GameType {
  CASH = 'CASH',
  TOURNAMENT = 'TOURNAMENT',
  FUN = 'FUN'
}

export enum Speed {
  REGULAR = 'REGULAR',
  TURBO = 'TURBO',
  HYPER = 'HYPER'
}

export interface PokerTable {
  id: string;
  creatorId?: string; // For Host-to-Earn
  name: string;
  smallBlind: number;
  bigBlind: number;
  seats: 6 | 9;
  occupiedSeats: number;
  buyInMin: number;
  buyInMax: number;
  speed: Speed;
  rakeCap: number; // Max rake in USDT per hand
  type?: GameType;
  isPrivate?: boolean;
  password?: string;
}

export interface Tournament {
  id: string;
  creatorId?: string; // For Host-to-Earn
  name: string;
  buyIn: number;
  prizePool: number;
  registeredPlayers: number;
  maxPlayers: number;
  startTime: string; // ISO date string
  speed: Speed;
  status: 'REGISTERING' | 'LIVE' | 'FINISHED';
  winnersCount?: string; // e.g. "15" or "Top 10%"
  distribution?: string; // e.g. "Standard", "WinnerTakesAll"
  startingChips?: number;
  seats?: 6 | 9; // Added seats property
  isPrivate?: boolean;
  password?: string;
}

export interface GameStats {
  totalHands: number;
  winRate: number; // bb/100
  totalWinnings: number;
  roi: number;
  bestHand: string;
  tournamentsPlayed: number;
  tournamentsWon: number;
}
