import React, { useState } from 'react';
import { Card } from '../components/ui/Card';
import { ChevronDown, ChevronUp, HelpCircle } from 'lucide-react';

export const FAQ: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in duration-500 pb-12">
      
      <div className="text-center space-y-4 pt-8">
        <h1 className="text-4xl font-bold text-white">Frequently Asked Questions</h1>
        <p className="text-gray-400">Everything you need to know about SOLPOKER X.</p>
      </div>

      <div className="space-y-4">
          <FAQItem 
            question="What is SOLPOKER X?" 
            answer="SOLPOKER X is a decentralized poker platform built on the Solana blockchain. It offers a transparent, non-custodial gaming experience where players can play Texas Hold'em using cryptocurrency without depositing funds into a centralized casino wallet."
          />
          <FAQItem 
            question="Do I need to deposit funds to play?" 
            answer="No. Unlike traditional poker sites, SOLPOKER X is non-custodial. You connect your Solana wallet (like Phantom or Solflare), and buy-ins for tables are executed as individual transactions. Your funds remain in your wallet until you decide to join a table, and winnings are sent directly back to your wallet."
          />
          <FAQItem 
            question="Is the game fair? How is the shuffle generated?" 
            answer="Yes. We use a Provably Fair Random Number Generation (RNG) system. The deck shuffle is determined by a combination of a Server Seed (hashed and shown before the hand) and a Client Seed (provided by you). You can verify the fairness of every hand in the game settings to ensure the outcome was not manipulated."
          />
          <FAQItem 
            question="What fees does the platform charge?" 
            answer="We charge a standard rake on Cash Games (typically 3-5%, capped). These fees are redistributed back to the community via Host-to-Earn rewards, Referrals, and the Monthly Jackpot."
          />
          <FAQItem 
            question="How does Host-to-Earn work?" 
            answer="Any user can create (host) a cash game table. As the creator, you earn a percentage (30% - 40%) of all rake generated by that table. This incentivizes players to run their own communities within the platform."
          />
          <FAQItem 
            question="What are the platform fees used for?" 
            answer="Platform fees are redistributed to the community. 30-40% goes to table hosts, 5-20% to referrers, 5% to the monthly jackpot for top players, 5% to the global partner pool, and the remainder supports platform development and operations."
          />
          <FAQItem 
            question="Can I play on mobile?" 
            answer="Yes! SOLPOKER X is fully optimized for mobile devices. We recommend using Portrait mode for the best experience on phones."
          />
          <FAQItem 
            question="What happens if I get disconnected during a hand?" 
            answer="If you disconnect, your hand will be Check/Folded automatically when your time bank runs out. Since funds are held in a smart contract for the duration of the buy-in, your remaining stack is safe. You can reconnect and rejoin the table, or your stack will be returned to your wallet after a timeout period."
          />
      </div>

      <Card className="bg-sol-blue/10 border-sol-blue/30 text-center">
          <HelpCircle className="mx-auto text-sol-blue mb-2" size={32}/>
          <h3 className="text-lg font-bold text-white mb-2">Still have questions?</h3>
          <p className="text-gray-400 mb-4">Join our community on Telegram to chat with support and other players.</p>
          <a href="https://t.me/solpokerx" target="_blank" className="inline-block bg-sol-blue text-white px-6 py-2 rounded-lg font-bold hover:bg-blue-600 transition-colors">
              Contact Support
          </a>
      </Card>

    </div>
  );
};

const FAQItem = ({ question, answer }: { question: string, answer: string }) => {
    const [isOpen, setIsOpen] = useState(false);

    return (
        <Card 
            className={`cursor-pointer transition-all duration-300 border hover:border-white/20 ${isOpen ? 'bg-white/10 border-white/20' : 'bg-white/5 border-white/5'}`}
            onClick={() => setIsOpen(!isOpen)}
        >
            <div className="flex justify-between items-center">
                <h3 className="font-bold text-white text-lg">{question}</h3>
                {isOpen ? <ChevronUp className="text-sol-green" /> : <ChevronDown className="text-gray-400" />}
            </div>
            {isOpen && (
                <div className="mt-4 pt-4 border-t border-white/10 text-gray-300 leading-relaxed animate-in slide-in-from-top-2">
                    {answer}
                </div>
            )}
        </Card>
    );
}